# Generated by Django 5.0.3 on 2024-03-10 09:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=accounts.models.get_default_nickname, max_length=10)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/%Y/%m/%d/')),
            ],
        ),
    ]
