# Generated by Django 5.0.3 on 2024-03-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='title',
            new_name='promo_code',
        ),
    ]
