# Generated by Django 5.0.3 on 2024-03-10 10:24

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_view_count_alter_post_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=tinymce.models.HTMLField(),
        ),
    ]
